openapi: 3.0.2
info:
  version: 1.0.0
  title: ExploreTheBuild Item Recovery
  contact:
    name: justCoding
    email: justus@justcoding.tech
  license:
    name: Mozilla Public License Version 2.0
    url: 'https://www.mozilla.org/en-US/MPL/2.0/'
  x-logo:
    url: 'https://avatars.githubusercontent.com/u/81708234?s=200&v=4'
  description: >
    This api allows users to interact with the EtB Item Recovery database.
tags:
  - name: User
    description: Operations about user
servers:
  - url: 'https://api.justcoding.tech/'
paths:
  '/users/{userid}':
    $ref: 'paths/users@{userid}.yaml'
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: query
      name: api_key